version: "2"
services:
    nginx-proxy:    # reverse proxy
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./mounts/vhost.d:/etc/nginx/vhost.d
        - ./mounts/certs:/etc/nginx/certs
        - ./mounts/webroot:/usr/share/nginx/html

    letsencrypt-nginx-proxy-companion: # should automatically handle
      image: jrcs/letsencrypt-nginx-proxy-companion #letsencrypt config
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - ./mounts/certs:/etc/nginx/certs
      volumes_from:
        - "nginx-proxy"
#      environment:
#        ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
# Use the above URL until you're sure everything works, lest you be banned!
