# docker-compose.yaml
version: "2"
services:
    resume:         # my resume
      image: nginx
      volumes:
        - ./config:/etc/nginx
        - ./webroot:/usr/share/nginx/html
      environment:
        VIRTUAL_HOST:       s.scott.tams.tech
        LETSENCRYPT_HOST:   s.scott.tams.tech
        LETSENCRYPT_EMAIL:  sysadmin@tams.tech
      expose:
        - '80'
      networks:
        - reverse_proxy_default
networks:
  reverse_proxy_default:
    external: true
